// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUa_JGnp-ZHfY76mnnK_ASlDhbKR3mQbA',
    appId: '1:375118526069:web:6b121c00a2944b5d3c2a3c',
    messagingSenderId: '375118526069',
    projectId: 'smokeguard-ac1bb',
    authDomain: 'smokeguard-ac1bb.firebaseapp.com',
    storageBucket: 'smokeguard-ac1bb.firebasestorage.app',
    measurementId: 'G-F71ECVSFGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsOHis4LJUtkYD7oC1oh8alYjpHDPyAI',
    appId: '1:375118526069:android:96d222f2c56c21953c2a3c',
    messagingSenderId: '375118526069',
    projectId: 'smokeguard-ac1bb',
    storageBucket: 'smokeguard-ac1bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6y3E79mklTcl7SXotbSoqdxG1S0ZPfo',
    appId: '1:375118526069:ios:0c120522625026483c2a3c',
    messagingSenderId: '375118526069',
    projectId: 'smokeguard-ac1bb',
    storageBucket: 'smokeguard-ac1bb.firebasestorage.app',
    iosBundleId: 'com.example.smokeGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6y3E79mklTcl7SXotbSoqdxG1S0ZPfo',
    appId: '1:375118526069:ios:0c120522625026483c2a3c',
    messagingSenderId: '375118526069',
    projectId: 'smokeguard-ac1bb',
    storageBucket: 'smokeguard-ac1bb.firebasestorage.app',
    iosBundleId: 'com.example.smokeGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUa_JGnp-ZHfY76mnnK_ASlDhbKR3mQbA',
    appId: '1:375118526069:web:6602180d46fc42803c2a3c',
    messagingSenderId: '375118526069',
    projectId: 'smokeguard-ac1bb',
    authDomain: 'smokeguard-ac1bb.firebaseapp.com',
    storageBucket: 'smokeguard-ac1bb.firebasestorage.app',
    measurementId: 'G-KK36PXY3XH',
  );
}
